config/routes.rb
Rails.application.routes.draw do


    resources :cities do
      resources :population
    end
  
	root 'home#index'

  post '/cities/new', controller: 'cities', action: 'new'

  delete 'city', controller: 'cities', action: 'destroy'

  put 'city', controller: 'cities', action: 'update'
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	
	def index
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index

  end

  def new
    @city = City.new
  end

  def create
     duplicate_entry = duplicate_entry?
     if duplicate_entry == true
       render text: "There's a duplicate"
     else
       @city = City.create(city_params)
       redirect_to '/'
     end
  end

  def edit
  end

  def update
    this_city.update(:name => params[:city][:name])
    this_city.update(:state => params[:city][:state])
    redirect_to :back
  end

  def destroy
    this_city.destroy
    redirect_to :back
  end

  #PRIVATE METHODS
  private
  def city_params
    params.require(:city).permit(:name, :state)
  end

  private
  def this_city
    city = City.find_by(:id => params[:id])
    return city
  end

  private
  def duplicate_entry?
    submitedCity = params[:city][:name]
    submitedCityState = params[:city][:state]
    matchingEntries = ::City.where(name: submitedCity)

    puts matchingEntries
    i = 0
    matchingEntries.each do | match |
      if match[:state] == submitedCityState
        i += 1
      end
    end

    if i > 0
      return true
    else
      return false
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		#@city = City.new
		#@city.name = "Los Angeles"
		#@city.state = "California"
		
		#if !::City.exists?(name: @city.name) && !::City.exists?(name: @city.state)
		#	@city.save
		#end
	end
	
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/index.html.erb
<h1>Kenmertics Admin Panel</h1>

<%= link_to('Generate New Data',new_city_path) %>

<%  %>

app/views/cities/edit.html.erb
<% city = City.find_by(:id => params[:id]) %>

<h1>Edit City Data For <%= city[:name] %> </h1>
<%= form_for city, url: {action: "update"},method:"put" do |f| %>
    <%= f.label(:name, "City Name") %>
    <%= f.text_field :name, placeholder: "City Name" %>
    <%= f.label(:state, "City State") %>
    <%= f.text_field :state, placeholder: "City State" %>
    <%= f.submit "Update Data" %>
<% end %>

app/views/cities/new.html.erb
<h1>Please Enter City Data:</h1>
<%= form_for @city, url: {action: "create"} do |f|%>
    <%= f.label(:name, "City Name")%>
    <%= f.text_field :name %>
    <%= f.label(:state, "City State")%>
    <%= f.text_field :state %>
    <%= f.submit "Add Data" %>
<% end %>

app/views/home/index.html.erb
<h1>We are making progress.</h1>
<%= button_to('Generate New Data',new_city_path) %>
<ul>
  <% City.all.each do | city | %>
      <li>
        <span><%= city.name %>, <%= city.state %></span>
        <span><%= button_to("Edit",edit_city_path(city.id),{:method => :get})%></span>
        <span><%= button_to("Delete", city, :method => :delete, data: {:confirm => 'Are you sure?'})%></span>
      </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlankApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>